dependencies:
- name: redis
  version: 10.3.1
  repository: https://kubernetes-charts.storage.googleapis.com
- name: mongodb
  version: 7.6.3
  repository: https://kubernetes-charts.storage.googleapis.com
