dependencies:
- name: redis
  version: 10.5.7
  repository: https://kubernetes-charts.storage.googleapis.com
- name: mongodb
  version: 7.8.7
  repository: https://kubernetes-charts.storage.googleapis.com
