dependencies:
- name: redis
  version: 10.3.2
  repository: https://kubernetes-charts.storage.googleapis.com
- name: mongodb
  version: 7.6.4
  repository: https://kubernetes-charts.storage.googleapis.com
