dependencies:
- name: redis
  version: 10.4.2
  repository: https://kubernetes-charts.storage.googleapis.com
- name: mongodb
  version: 7.8.3
  repository: https://kubernetes-charts.storage.googleapis.com
